# Generated by Django 4.1.3 on 2022-12-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_App', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
