# Generated by Django 4.1.4 on 2022-12-20 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_App', '0008_orderedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api_App.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_App.userprofile'),
        ),
    ]
