# Generated by Django 4.1.4 on 2022-12-21 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_App', '0011_alter_orderedproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_products', to='api_App.product'),
        ),
    ]
