# Generated by Django 4.1.4 on 2022-12-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_App', '0012_alter_orderedproduct_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
