# Generated by Django 4.1.4 on 2022-12-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_App', '0013_orderedproduct_confirm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedproduct',
            old_name='confirm',
            new_name='confirmed',
        ),
    ]
